apiVersion: batch/v1
kind: Job
metadata:  
  generateName: kmeter-  
spec:
  template: 
    metadata:
      labels: 
        aadpodidbinding: "kmeter"
    spec:
      restartPolicy: "Never"
      containers:
        - name: kmeter
          image: danielmeixner/kmeter:latest      
          env: 
            - name: "KMETER_NAMESPACE"
              value: "default"
            - name: "KMETER_PODNAME"
              value: "memory-demo"
            - name: "KMETER_DEBUG"
              value: "true"
            - name: "KMETER_INTERVAL"
              value: "5000"
            - name: "KMETER_TIME"
              value: "30"
            