apiVersion: batch/v1
kind: Job
metadata:  
  generateName: kmeter-
  labels:
    aadpodidbinding: "kmeter"
spec:
  template: 
    metadata:
      labels: 
        aadpodidbinding: "kmeter"
    spec:
      restartPolicy: "Never"
      containers:
        - name: kmeter
          image: danielmeixner/kmeter:latest      
          env: 
            - name: "KMETER_NAMESPACE"
              value: "default"
            - name: "KMETER_PODNAME"
              value: "compute-svc-sfs-2"
            - name: "KMETER_DEBUG"
              value: "false"
            - name: "KMETER_INTERVAL"
              value: "5000"
            - name: "KMETER_TIME"
              value: "30"
            