# Demo Pod with 2 containers, one of them burning memory.
apiVersion: v1
kind: Pod
metadata:
  name: memory-demo  
spec:
  containers:
  - name: memory-demo-ctr
    image: polinux/stress
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]
  - name: nginx 
    image: nginx
  - name: nginx2
    image: nginx
---