apiVersion: batch/v1
kind: Job
metadata:  
  generateName: kmeter-
spec:
  template: 
    spec:
      restartPolicy: "Never"
      containers:
        - name: kmeter
          image: danielmeixner/kmeter:latest      
          env: 
            - name: "METER_NAMESPACE"
              value: "default"
            - name: "METER_PODNAME"
              value: "nginx-dbddb74b8-zzpn4"
            - name: "METER_DEBUG"
              value: "false"
            - name: "METER_INTERVAL"
              value: "5000"
            - name: "METER_TIME"
              value: "30"
            